--06.05
--영화예매 프로젝트
--1. 회원정보, (MEMBERS)
--2. 영화정보, (MOVIES)
--3. 극장정보,  (THEATERS)
--4. 상영스케쥴, (SCHEDULES)
--5. 예매내역 (RESERVATIONS)
--영화 정보 테이블
    CREATE TABLE MOVIES(
    MVCODE NVARCHAR2(5),   --영화코드(PK)
    MVTITLE NVARCHAR2 (30), --영화제목
    MVDIRECTOR NVARCHAR2(20), -- 영화 감독
    MVACTORS NVARCHAR2(50), --배우
    MVGENRE NVARCHAR2(20),  --장르
    MVINFO NVARCHAR2(20),   --기본정보
    MVOPEN DATE,            --개봉일
    MVPOSTER NVARCHAR2(50)  --포스터
);
ALTER TABLE MOVIES
ADD CONSTRAINT PK_MOVIES PRIMARY KEY(MVCODE);

--극장정보 테이블(THEATHERS - TH)
CREATE TABLE THEATERS(
    THCODE NVARCHAR2(5),    --극장코드PK
    THNAME NVARCHAR2(20),   --극장이름
    THLOC NVARCHAR2(10),    --지역구분
    THADDR NVARCHAR2(30),   --극장주소
    THTEL NVARCHAR2(15)      --전화번호
);
ALTER TABLE THEATERS
ADD CONSTRAINT PK_THEATERS PRIMARY KEY(THCODE);

--상영스케쥴(SCHEDULES - SC)
-- 영화정보 MVCODE, 극장정보THCODE, 상영관, 날짜시간, 
CREATE TABLE SCHEDULES(
    MVCODE NVARCHAR2(5), --영화코드 FK MOVIES MVCODE
    THCODE NVARCHAR2(5), --극장코드 FK THEATERS THCODE
    SCREENS NVARCHAR2(20), --상영관
    SCDATE DATE           --날짜시간
);
ALTER TABLE SCHEDULES
ADD CONSTRAINT PK_SCHEDULES PRIMARY KEY(THCODE, SCREENS, SCDATE);
ALTER TABLE SCHEDULES
ADD CONSTRAINT FK_MVCODE_SC FOREIGN KEY (MVCODE)
REFERENCES THEATERS(THCODE);

INSERT INTO SCHEDULES
VALUES('M0001','T0001','1관', TO_DATE('2023-06-06 13:40'));
INSERT INTO SCHEDULES
VALUES('M0001','T0001','1관', TO_DATE('2023-06-07 13:40'));
INSERT INTO SCHEDULES
VALUES('M0001','T0001','1관', TO_DATE('2023-06-06 17:00'));

INSERT INTO SCHEDULES
VALUES('M0001','T0001','1관', TO_DATE('2023-06-06 13:40')); --등록 X

--예매 정보 RESERVATIONS - RE
--예매자아이디(FK - MEMBERS(MID),
--영화정보(MOVIES),
--극장정보(THEATERS),
--상영관(SCHEDULES),
--날짜시간(SCHEDULES),
--예매인원수
--RESERVATIONS 테이블은 SCHEDULES 테이블을 참조(외래키 - FOREIGN KEY)
--RESERVATIONS 테이블은 SCHEDULES 테이블의 PRIMARY KEY를 참조
--SCHEDULES 테이블의 PRIMARY KEY는 THCODE, SCREENS, SCDATE
CREATE TABLE RESERVATIONS(
    RECODE NVARCHAR2(5), --예매코드
    REMID NVARCHAR2(10), -- 예매자 아이디
    THCODE NVARCHAR2(5), --극장코드 FK THEATERS THCODE
    SCREENS NVARCHAR2(20), --상영관
    SCDATE DATE,            --날짜 시간
    RECOUNT NUMBER         --예매인원수
    );
ALTER TABLE RESERVATIONS
ADD CONSTRAINT PK_RESERVATIONS PRIMARY KEY (RECODE);

ALTER TABLE RESERVATIONS
ADD CONSTRAINT FK_RESERVATIONS FOREIGN KEY (THCODE, SCREENS, SCDATE)
REFERENCES SCHEDULES(THCODE, SCREENS, SCDATE);


SELECT * FROM SCHEDULES;