--====================================06.07========================================
--ORACLE - 문자 함수
--TO_CHAR() - 날짜형 >> 문자형
--TO_DATE() - 문자형 >> 날짜형
--UPPER() - 모두 대문자로 변경
--LOWER() - 모두 소문자로 변경
SELECT UPPER('student'), LOWER('STudENT')
FROM DUAL;

SELECT * FROM EMP WHERE UPPER(ENAME) = 'allen';

SELECT * FROM EMP WHERE LOWER(ENAME) = 'allen';

--INITCAP(): 첫글자를 대문자로, 나머지는 소문자로
SELECT INITCAP('STUDENT'), INITCAP('student'), INITCAP('stUDent')
FROM DUAL;

--LENGTH() : 문자열의 길이를 확인
SELECT LENGTH('STUDENT') FROM DUAL;

SELECT ENAME, LENGTH(ENAME)
FROM EMP;

SELECT MID, LENGTH(MID)
FROM EMP;

--LENGHTB(): 문자의 BYTE 확인
SELECT LENGTH('STUDENT'), LENGTHB('STUDENT') FROM DUAL;
SELECT LENGTH('학생'), LENGTHB('학생'),LENGTHB('학'),LENGTHB('ㅎ') FROM DUAL;

--SUBSTR(문자형데이터, 시작위치): 문자열의 일부를 추출
SELECT SUBSTR('STUDENT',1), SUBSTR('STUDENT',3) FROM DUAL;

--SUBSTR(문자형데이터, 시작위치,글자수): 문자열의 일부를 추출
SELECT SUBSTR('STUDENT',3), SUBSTR('STUDENT',3,4) FROM DUAL;

SELECT ENAME, SUBSTR(ENAME,2), SUBSTR(ENAME,2,2) FROM EMP;

--INSTR('문자형데이터','찾을문자',시작위치 )
SELECT INSTR('STUDENT','T'), INSTR('STUDENT','T',3) FROM DUAL;

SELECT INSTR('STUDENT','DEN') FROM DUAL;
SELECT INSTR('STUDENT','Z') FROM DUAL;
SELECT INSTR('STUDENT','SUT') FROM DUAL;

--REPLACE('문자형데이터','대상문자','변경할문자') : 특정 문자를 바꾸는 함수 
SELECT REPLACE('010-1111-2222','-','*') FROM DUAL;

SELECT ENAME, REPLACE(ENAME,'A','에이') FROM EMP;
SELECT ENAME, REPLACE(ENAME,'A'), REPLACE(ENMAE,'A','') FROM EMP;

--LPAD('문자형데이터', 전체글자수, '채워줄문자')
--RPAD()
SELECT LPAD('STU',10,'-'), RPAD('STU',10,'-') FROM DUAL;

SELECT LPAD('STUDENT',5,'-'), RPAD('STUDENT',5,'-') FROM DUAL;

-- '230605-3456789' 조회 결과 >> '203607-3******' 출력
SELECT RPAD(SUBSTR ('230605-3456789',1,8), 14,'*')
FROM DUAL;
--'양기두' >> '양*두'
SELECT MNAME, REPLACE(MNAME,SUBSTR(MNAME,2,1),'*')
FROM MEMBERS;
SELECT MNAME
FROM MEMBERS;


--============================06.08===============================
--숫자함수
--절대값
select abs(5),ABS(-10) FROM DUAL;

--반올림 : ROUND(숫자,반올림 자리수)
SELECT 1234.5678, ROUND(1234,5678),ROUND(1234.5678,0),ROUND(1234.5678,1) FROM DUAL;
SELECT 1234.5678, ROUND(1234.5678,-1), ROUND(1234.5678,-2) FROM DUAL;

--버림 : TRUNC(숫자, 자리수)
SELECT 1234.5678, TRUNC(1234,5678),TRUNC(1234.5678,0),TRUNC(1234.5678,1) FROM DUAL;
SELECT 1234.5678, TRUNC(1234.5678,-1), TRUNC(1234.5678,-2) FROM DUAL;

--CEIL(숫자)
--FLOOR(숫자)
SELECT 1234.5678, CEIL(1234.5678), FLOOR(1234.5678) FROM DUAL;

--날짜형
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE -1 FROM DUAL; --하루전 -를 +로 하면 하루 후
SELECT SYSDATE -1/24 FROM DUAL; --한시간전
SELECT SYSDATE -30/24/60 FROM DUAL; --삼십분전

--ADD_MONTHS(날짜형, 개월수)
SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;

--날짜 연산
SELECT SYSDATE - ODDATE,SYSDATE, ODDATE FROM ORDERS;

SELECT SYSDATE - SYSDATE,SYSDATE, ODDATE FROM ORDERS;

--MONTHS_BETWEEN(날짜형, 날짜형)
SELECT MONTHS_BETWEEN(SYSDATE,'2023-01-10')FROM DUAL;
SELECT MONTHS_BETWEEN('2023-01-10',SYSDATE)FROM DUAL;

--NEXT_DAY(날짜, 찾을 요일)
SELECT NEXT_DAY(SYSDATE, '월') FROM DUAL;

--LAST_DAY(날짜)
SELECT LAST_DAY(SYSDATE), LAST_DAY('2023-07-01') FROM DUAL;

--TO_CHAR()
SELECT ODDATE, TO_CHAR(ODDATE,'YYYY') AS 연도,
TO_CHAR(ODDATE,'MM') AS 월,
TO_CHAR(ODDATE,'DD') AS 일
FROM ORDERS;

SELECT ODDATE,
        TO_CHAR(ODDATE,'MON'),
        TO_CHAR(ODDATE,'DAY'),
        TO_CHAR(ODDATE,'DY'),
        TO_CHAR(ODDATE,'W'),
        TO_CHAR(ODDATE,'WW'),
        TO_CHAR(SYSDATE,'W')
        FROM ORDERS;
--NVL(컬럼, 대체값), NVL2(컬럼, NULL이 아닌경우, NULL인경우)
SELECT ENAME, COMM,NVL(COMM,10000) FROM EMP;
SELECT ENAME, COMM, NVL2(COMM,'COMM있음','COMM없음') FROM EMP;